# Generated by Django 3.2.9 on 2021-11-08 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('vacuna', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(17, 0))),
                ('canales', models.IntegerField(default=0)),
                ('espera_maxima', models.IntegerField(default=0)),
                ('longitud_cola', models.IntegerField(default=0)),
                ('habilitada', models.BooleanField(default=True)),
                ('imagen', models.ImageField(default='default.svg', upload_to='img/%y')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
