# Generated by Django 3.2.9 on 2021-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='canales',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='espera_maxima',
        ),
        migrations.AddField(
            model_name='sede',
            name='prom_atendidas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sede',
            name='prom_llegadas',
            field=models.FloatField(default=0.0),
        ),
    ]
