# Generated by Django 3.0.7 on 2021-11-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('To-Do', 'To-Do task'), ('In Progress', 'In progress task'), ('Finished', 'Task as finish')], default='To-Do', max_length=15),
        ),
    ]
